name: Build & Deploy User Page

on:
  push:
    branches: [ main ]

permissions:
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust & Wasm Target
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          targets: wasm32-unknown-unknown

      - name: Install Trunk
        run: cargo install trunk

      - name: Build with Trunk
        run: trunk build --release --public-url "/"

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Page Artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
