# .github/workflows/pages.yml
name: Deploy Jekyll site to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'

      - run: gem install bundler
      - run: bundle install

      - run: bundle exec jekyll build --destination _site

      - uses: actions/configure-pages@v3

      - uses: actions/upload-pages-artifact@v1   # ← make sure it’s upload-pages-artifact@v1

      - uses: actions/deploy-pages@v1
